function fid = logger_init(problem_name)

timestamp = datestr(now,'yyyymmdd_HHMMSS');

log_dir = fullfile( ...
    'results', ...
    problem_name, ...
    'logs');

if ~exist(log_dir,'dir')
    mkdir(log_dir);
end

logfile = fullfile( ...
    log_dir,...
    sprintf('%s_%s.log', ...
    problem_name,...
    timestamp));

fid = fopen(logfile,'w');

logger(fid,'INFO',...
    '================================================================================');

logger(fid,'INFO',...
    'STARTING %s',upper(problem_name));

logger(fid,'INFO',...
    '================================================================================');

end