function logger_exception(fid,ME)

logger(fid,'ERROR', ...
    '============================================================');

logger(fid,'ERROR', ...
    'EXCEPTION OCCURRED');

logger(fid,'ERROR', ...
    '============================================================');

logger(fid,'ERROR', ...
    'Message: %s', ...
    ME.message);

for k = 1:length(ME.stack)

    logger(fid,'ERROR', ...
        'File: %s | Function: %s | Line: %d', ...
        ME.stack(k).file,...
        ME.stack(k).name,...
        ME.stack(k).line);

end

logger(fid,'ERROR', ...
    '============================================================');

end